export const TERMINAL_CONSTANTS = {
  COMMANDS: {
    READY: 'ready',
    INIT: 'init',
    INPUT: 'input',
    OUTPUT: 'output',
    RESIZE: 'resize',
    CLEAR: 'clear',
    EXIT: 'exit',
    SPLIT: 'split',
    TERMINAL_CREATED: 'terminalCreated',
    TERMINAL_REMOVED: 'terminalRemoved',
    FOCUS_TERMINAL: 'focusTerminal',
    GET_SETTINGS: 'getSettings',
    UPDATE_SETTINGS: 'updateSettings',
    SETTINGS_RESPONSE: 'settingsResponse',
    TERMINAL_CLOSED: 'terminalClosed',
  },
  DELAYS: {
    TERMINAL_REMOVE_DELAY: 2000,
    BUFFER_FLUSH_INTERVAL: 16,
    RESIZE_DEBOUNCE_DELAY: 150,
    STATUS_HIDE_DELAY: 3000,
    ERROR_STATUS_DELAY: 5000,
    HOVER_STATUS_DELAY: 1000,
    FADE_DURATION: 200,
  },
  SIZES: {
    MIN_TERMINAL_HEIGHT: 100,
    STATUS_BAR_HEIGHT: 24,
    HEADER_HEIGHT: 36,
    TERMINAL_HEADER_HEIGHT: 32,
    SPLITTER_HEIGHT: 4,
    MIN_CONTAINER_WIDTH: 200,
    MIN_CONTAINER_HEIGHT: 100,
  },
} as const;

export const THEME_CONSTANTS = {
  DARK_THEME: {
    background: '#1e1e1e',
    foreground: '#cccccc',
    cursor: '#ffffff',
    cursorAccent: '#000000',
    black: '#000000',
    red: '#cd3131',
    green: '#0dbc79',
    yellow: '#e5e510',
    blue: '#2472c8',
    magenta: '#bc3fbc',
    cyan: '#11a8cd',
    white: '#e5e5e5',
    brightBlack: '#666666',
    brightRed: '#f14c4c',
    brightGreen: '#23d18b',
    brightYellow: '#f5f543',
    brightBlue: '#3b8eea',
    brightMagenta: '#d670d6',
    brightCyan: '#29b8db',
    brightWhite: '#ffffff',
  },
  LIGHT_THEME: {
    background: '#ffffff',
    foreground: '#333333',
    cursor: '#000000',
    cursorAccent: '#ffffff',
    black: '#000000',
    red: '#cd3131',
    green: '#00bc00',
    yellow: '#949800',
    blue: '#0451a5',
    magenta: '#bc05bc',
    cyan: '#0598bc',
    white: '#555555',
    brightBlack: '#666666',
    brightRed: '#cd3131',
    brightGreen: '#14ce14',
    brightYellow: '#b5ba00',
    brightBlue: '#0451a5',
    brightMagenta: '#bc05bc',
    brightCyan: '#0598bc',
    brightWhite: '#a5a5a5',
  },
} as const;

export const UI_CONSTANTS = {
  SIZES: {
    HEADER_HEIGHT: 36,
    TITLE_FONT_SIZE: 14,
    TERMINAL_ICON_SIZE: 18,
    SAMPLE_ICON_SIZE: 18,
    CODICON_SIZE: 18,
    BADGE_MIN_WIDTH: 20,
    ICON_BUTTON_SIZE: 28,
  },
  SPACING: {
    HEADER_PADDING: 12,
    TITLE_GAP: 10,
    ICON_GAP: 2,
    ICON_PADDING: 6,
  },
  ANIMATION: {
    TRANSITION_DURATION: 300,
    FADE_DURATION: 200,
    SLIDE_DURATION: 250,
  },
} as const;

export const SAMPLE_ICONS = [
  { icon: '➕', title: 'New Terminal (Use panel button)' },
  { icon: '⫶', title: 'Split Terminal (Use panel button)' },
  { icon: '🧹', title: 'Clear Terminal (Use panel button)' },
  { icon: '🗑️', title: 'Kill Terminal (Use panel button)' },
  { icon: '⚙️', title: 'Settings (Use panel button)' },
] as const;

export const CSS_CLASSES = {
  STATUS: 'status',
  STATUS_INFO: 'status-info',
  STATUS_SUCCESS: 'status-success',
  STATUS_ERROR: 'status-error',
  STATUS_WARNING: 'status-warning',
  SAMPLE_ICON: 'sample-icon',
  SAMPLE_ICONS: 'sample-icons',
  HELP_TOOLTIP: 'help-tooltip',
  TERMINAL_TAB: 'terminal-tab',
  SPLIT_CONTAINER: 'split-terminal-container',
} as const;
